/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hr.ericsson.etkc.ebusiness;

public class AppLauncher {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	Main.main(args);
    	  
	}
    
  
}
