/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hr.ericsson.etkc.ebusiness;

public class AppLauncher {	
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	System.out.println("Working Directory = " + System.getProperty("user.dir"));
    	System.loadLibrary("opencv_java450");
    	Main.main(args);
    	  
	}
    
  
}
