/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FaceRecognition;

import org.junit.Test;

import hr.ericsson.etkc.ebusiness.AppLauncher;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        AppLauncher classUnderTest = new AppLauncher();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
